import type { ProductWithSeller } from "./types/database";

export const SAMPLE_PRODUCTS: ProductWithSeller[] = [
  {
    id: "sample-sepeda-lipat",
    seller_id: "seller-1",
    nama_barang: "Sepeda Lipat Polygon Urbano 3 Mulus",
    deskripsi:
      "Dijual sepeda lipat Polygon Urbano 3 warna hitam doff. Kondisi 95% mulus, jarang dipakai, ban masih tebal, lipatan kencang tanpa kendala. Siap COD di sekitar Gubeng / Unair B atau diantar kurir.",
    kategori_id: "transportasi",
    kondisi: "Bekas - Layak Pakai",
    harga_input: 1350000,
    harga_jual: 1450000,
    berat_kg: 12,
    foto_urls: [
      "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=700&auto=format&fit=crop&q=80",
    ],
    lat: -7.2654,
    lng: 112.7538,
    status: "Tersedia",
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    kategori: { id: "transportasi", nama_kategori: "Transportasi" },
    seller: {
      id: "seller-1",
      nama_lengkap: "Dimas Anggara",
      status_verifikasi: "verified",
      kecamatan_id: 8,
      kecamatan: { id: 8, nama_kecamatan: "Gubeng" },
    },
  },
  {
    id: "sample-meja-kursi-belajar",
    seller_id: "seller-2",
    nama_barang: "Meja Belajar Kayu Minimalis + Kursi Ergonomis",
    deskripsi:
      "Meja belajar kayu solid ukuran 100x50 cm lengkap dengan kursi putar ergonomis. Cocok untuk kamar kos atau kamar tidur. Kondisi kokoh dan bersih.",
    kategori_id: "perabot",
    kondisi: "Bekas - Layak Pakai",
    harga_input: 160000,
    harga_jual: 180000,
    berat_kg: 8,
    foto_urls: [
      "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=700&auto=format&fit=crop&q=80",
    ],
    lat: -7.2912,
    lng: 112.7932,
    status: "Tersedia",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    kategori: { id: "perabot", nama_kategori: "Perabot & Rumah Tangga" },
    seller: {
      id: "seller-2",
      nama_lengkap: "Sarah Putri",
      status_verifikasi: "verified",
      kecamatan_id: 23,
      kecamatan: { id: 23, nama_kecamatan: "Sukolilo" },
    },
  },
  {
    id: "sample-monitor-lg",
    seller_id: "seller-3",
    nama_barang: "Monitor LED LG 24 Inch Full HD IPS 75Hz",
    deskripsi:
      "Monitor LG 24MK600M 24 inch Full HD IPS 75Hz bezel-less. Layar jernih tanpa dead pixel, lengkap dengan kabel power dan kabel HDMI bawaan. Dijual karena ganti laptop.",
    kategori_id: "elektronik",
    kondisi: "Bekas - Layak Pakai",
    harga_input: 790000,
    harga_jual: 850000,
    berat_kg: 4,
    foto_urls: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=700&auto=format&fit=crop&q=80",
    ],
    lat: -7.3188,
    lng: 112.7712,
    status: "Tersedia",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    kategori: { id: "elektronik", nama_kategori: "Elektronik & Gadget" },
    seller: {
      id: "seller-3",
      nama_lengkap: "Reza Fahlevi",
      status_verifikasi: "verified",
      kecamatan_id: 18,
      kecamatan: { id: 18, nama_kecamatan: "Rungkut" },
    },
  },
  {
    id: "sample-buku-paket",
    seller_id: "seller-4",
    nama_barang: "Buku Paket Algoritma Pemrograman & Kalkulus",
    deskripsi:
      "Buku referensi kuliah original, edisi bahasa Indonesia. Kertas masih bersih, tidak ada coretan pulpen berlebih. Sangat bermanfaat untuk mahasiswa semester awal.",
    kategori_id: "buku",
    kondisi: "Bekas - Layak Pakai",
    harga_input: 55000,
    harga_jual: 65000,
    berat_kg: 1.5,
    foto_urls: [
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=700&auto=format&fit=crop&q=80",
    ],
    lat: -7.3012,
    lng: 112.7388,
    status: "Tersedia",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    kategori: { id: "buku", nama_kategori: "Buku & Alat Tulis" },
    seller: {
      id: "seller-4",
      nama_lengkap: "Ahmad Fauzi",
      status_verifikasi: "verified",
      kecamatan_id: 31,
      kecamatan: { id: 31, nama_kecamatan: "Wonokromo" },
    },
  },
  {
    id: "sample-dispenser-miyako",
    seller_id: "seller-5",
    nama_barang: "Dispenser Air Galon Miyako Hot & Normal",
    deskripsi:
      "Dispenser Miyako kondisi normal 100%, elemen pemanas bekerja cepat, bodi bersih tanpa noda membandel. Dijual karena sudah lulus dan mau pindah kota.",
    kategori_id: "perabot",
    kondisi: "Bekas - Layak Pakai",
    harga_input: 85000,
    harga_jual: 95000,
    berat_kg: 3,
    foto_urls: [
      "https://images.unsplash.com/photo-1585659722983-3a675dabf23d?w=700&auto=format&fit=crop&q=80",
    ],
    lat: -7.2711,
    lng: 112.7394,
    status: "Tersedia",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    kategori: { id: "perabot", nama_kategori: "Perabot & Rumah Tangga" },
    seller: {
      id: "seller-5",
      nama_lengkap: "Nadia Utami",
      status_verifikasi: "verified",
      kecamatan_id: 27,
      kecamatan: { id: 27, nama_kecamatan: "Tegalsari" },
    },
  },
  {
    id: "sample-rak-sepatu",
    seller_id: "seller-6",
    nama_barang: "Rak Sepatu Portable 5 Susun Rangka Besi",
    deskripsi:
      "Rak sepatu multifungsi 5 tingkat, rangka pipa besi tebal dan konektor plastik kuat. Muat hingga 15 pasang sepatu/sandal. Barang masih seperti baru.",
    kategori_id: "perabot",
    kondisi: "Baru",
    harga_input: 38000,
    harga_jual: 45000,
    berat_kg: 2,
    foto_urls: [
      "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=700&auto=format&fit=crop&q=80",
    ],
    lat: -7.2512,
    lng: 112.7612,
    status: "Tersedia",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    kategori: { id: "perabot", nama_kategori: "Perabot & Rumah Tangga" },
    seller: {
      id: "seller-6",
      nama_lengkap: "Budi Santoso",
      status_verifikasi: "verified",
      kecamatan_id: 25,
      kecamatan: { id: 25, nama_kecamatan: "Tambaksari" },
    },
  },
  {
    id: "sample-kipas-angin",
    seller_id: "seller-7",
    nama_barang: "Kipas Angin Berdiri Cosmos Stand Fan 16 Inch",
    deskripsi:
      "Kipas angin Cosmos 16-SDB stand fan 16 inci. Angin kencang, 3 level kecepatan, motor hening tidak berisik, swing kiri-kanan lancar. Lengkap dengan kartu garansi.",
    kategori_id: "elektronik",
    kondisi: "Bekas - Layak Pakai",
    harga_input: 125000,
    harga_jual: 140000,
    berat_kg: 5,
    foto_urls: [
      "https://images.unsplash.com/photo-1618941716939-553df3c6c278?w=700&auto=format&fit=crop&q=80",
    ],
    lat: -7.2723,
    lng: 112.7911,
    status: "Tersedia",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
    kategori: { id: "elektronik", nama_kategori: "Elektronik & Gadget" },
    seller: {
      id: "seller-7",
      nama_lengkap: "Fajar Nugraha",
      status_verifikasi: "verified",
      kecamatan_id: 15,
      kecamatan: { id: 15, nama_kecamatan: "Mulyorejo" },
    },
  },
  {
    id: "sample-keyboard-mechanical",
    seller_id: "seller-8",
    nama_barang: "Keyboard Mechanical RGB Wireless 65% Red Switch",
    deskripsi:
      "Keyboard mechanical 65% layout, triple connection (Bluetooth, 2.4Ghz Dongle, Type-C). Hotswappable red switch empuk dan quiet, RGB backlight menawan. Lengkap box & kabel.",
    kategori_id: "elektronik",
    kondisi: "Bekas - Layak Pakai",
    harga_input: 290000,
    harga_jual: 320000,
    berat_kg: 1,
    foto_urls: [
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=700&auto=format&fit=crop&q=80",
    ],
    lat: -7.2601,
    lng: 112.7422,
    status: "Tersedia",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    kategori: { id: "elektronik", nama_kategori: "Elektronik & Gadget" },
    seller: {
      id: "seller-8",
      nama_lengkap: "Kevin Pratama",
      status_verifikasi: "verified",
      kecamatan_id: 7,
      kecamatan: { id: 7, nama_kecamatan: "Genteng" },
    },
  },
];
